### ISSUE TITLE
Proposal: increment expected count w/ number

### ISSUE THREAD

**Issue by bkendall** [tjmehta/callback-count#2]
What do you think about doing something like this:

```javascript
var createCount = require('callback-count');
// really, really roughly (probably not this concise in real life)
var tasks = [/* some array of callbacky things */]
var count = createCount(cb);
// ... going along our merry way, maybe we expand tasks or something
count.inc(tasks.length);
tasks.forEach(function (t) { count.next(); });
```

I think that if you just call `.inc()` w/o args it would still only increment by one, but I've done this a few times in code. (maybe this is just a bad idea... why not just refactor so one could call `createCount(tasks.length, cb)`. maybe more options is good?)

**Comment by tjmehta** [comment]
I like this, it is more expressive than accepting the count in the factory.
